---
title       : Energy Consumption
subtitle    : In a domestic house
author      : Xavier Martí
job         : R student
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      #
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Description

The Shiny App I wrote displays energy consumption information:

- gas
- electricity
- water

for the years 2012 to 2014.

---
## Details

This is data from the energy consumption of a domestic house through years 2012 to 2014.

The accumulated consumption of Water, Gas and Electricity is measured each week and the difference with previous week is that week's consumption.

Further more, a formula is applied to compute an estimate price (expressed in
EUR) for the week's consumption.

---
## Example

Here are the first 10 lines of the Excel file (for the columns which interest
me, the ones I show in the barplot):

```{r head-10-lines, echo=FALSE}
data <- read.csv("../energyConsumptionData.csv", sep=",", header=T)
subset(data, select=c(Date,PriceGas,PriceElec,PriceWater))[1:10, ]
```

---
## Lessons learned

- Necessary to use reactive function as soon as I have 2 inputs or more.

- In the renderPlot function, the name of the dataframe must be followed by
  parentheses.

---
## Conclusion

- It is really impressive how easy it is to develop an interactive app with Shiny.

- It makes you wonder how many times could you have used it in life to create useful tools or presentations with small effort.

- Next time I will try making vertical axes scale dependant on displayed data. Water consumption chart was difficult to appreciate without this.
